# Generated by Django 2.1.1 on 2018-10-01 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_newevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newevent',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='newevent',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='newevent',
            name='imprint',
        ),
        migrations.RemoveField(
            model_name='newevent',
            name='status',
        ),
        migrations.AddField(
            model_name='newevent',
            name='address',
            field=models.CharField(default='No Address', max_length=200),
        ),
        migrations.AddField(
            model_name='newevent',
            name='iid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newevent',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=django.utils.timezone.now, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newevent',
            name='long',
            field=models.DecimalField(decimal_places=20, default=django.utils.timezone.now, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newevent',
            name='name',
            field=models.CharField(default='No Name', max_length=200),
        ),
        migrations.AddField(
            model_name='newevent',
            name='type',
            field=models.CharField(default='No Type', max_length=200),
        ),
    ]
