# Generated by Django 2.1.1 on 2018-09-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='incomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Coordinates for incoming service event', max_length=200)),
                ('serviceType', models.CharField(help_text='Description of service needed', max_length=200)),
                ('urgency', models.CharField(help_text='Urgency level of situation', max_length=200)),
                ('time', models.CharField(help_text='Time the event came in', max_length=200)),
            ],
            options={
                'ordering': ['urgency'],
            },
        ),
    ]
