# Generated by Django 2.1.1 on 2018-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181001_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='newevent',
            name='long',
            field=models.DecimalField(decimal_places=20, default=1, max_digits=20),
        ),
    ]
