# Generated by Django 2.1.1 on 2018-10-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181001_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newEvent',
        ),
    ]
